-
  hosts: Routers
  connection: local
  tasks:
    - include_vars: secrets.yaml
    - 
      ios_facts:
        provider: "{{ provider }}"
        gather_subset: all
      register: gather
    -
      copy: content="{{ gather | to_nice_json }}" dest="out/{{inventory_hostname}}_iosfacts.json"

#    debug: var=gather.stdout_lines

