-
  hosts: ALL 
  gather_facts: false
  connection: local
  tasks:
    - include_vars: secrets.yaml
    - ios_config:
        lines:
          - hostname {{ pays }}{{ ville }}{{ type }}{{ typeid }} 
        provider: "{{ provider }}"
