-
  hosts: ALL 
  gather_facts: false
  connection: local
  tasks:
    - ios_command:
        commands: "show run | s interface Loopback0" 
        provider:
          username: admin
          password: ingesup
          authorize: yes
      register: output
    - debug: var=output.stdout_lines
