-
  hosts: evagroup
  gather_facts: false
  connection: local
  tasks:
    - include_vars: secrets.yaml
    - ios_config:
        lines:
          - ip add 1.{{ france }}.1.{{ ip }} 255.255.255.255
          - description ip loopback
        parents: interface lo0
        provider: "{{ provider }}"
