-
  hosts: all 
  gather_facts: false
  connection: local
  tasks:
    - include_vars: secrets.yaml
    - name: Ajout interface loopback
      ios_config:
        lines:
          - ip add 1.{{ region }}.{{ site }}.{{ iplo0 }} 255.255.255.255
          - description ip loopback
        parents: interface lo0
        provider: "{{ provider }}"
