-
  hosts: Routers
  gather_facts: false
  connection: local
  tasks:
    - include_vars: secrets.yaml
    - name: Configure OSPF
      ios_config:
        lines:
	  - network 0.0.0.0 0.0.0.0 area 0
	parents:['router ospf 1']
        provider: "{{ provider }}"
