-
  hosts: all 
  gather_facts: false
  connection: local
  tasks:
    - ios_command:
        commands: "show run"
        provider:
          username: admin
          password: ingesup
          authorize: yes
      register: output
    - debug: var=output.stdout_lines
