-
  hosts: ALL 
  gather_facts: false
  connection: local
  tasks:
    - include_vars: secrets.yaml
    - name: Consultation des adresses ip des interfaces
      ios_command:
        commands: "show ip int br " 
        provider: "{{ provider }}"
      register: output
    - debug: var=output.stdout_lines
